### ISSUE TITLE
Failed to use this extension

### ISSUE THREAD

**Issue by sydwang** [FangStarNet/net.fangstar.LaravelCsrfToken#1]
I downloaded a copy. After copying the zip file in the extension directory, I extracted it. Then rebooting my Mac, I failed to load the extension. After checking the extension console, I managed to carry out the upload of this extension, by deleting the letters of '-master' from the directory name.
Without doing this, the extension couldn't be loaded.
When I was trying to set the value of X-CSRF-TOKEN as your instruction, I got a pop-up window which said this dynamic value doesn't have any input.
It doesn't work.
Would you help me?  Thank you very much.

**Comment by cook-coder** [comment]
Thank you for using this, and I'm sorry for your trouble.
I did not get any pop-up window, but here's my suggestion:
If you make a post request directly, the value of Laravel CSRF Token is null.
So, first you need make a get request, then the value of Laravel CSRF Token will be filled in.
I hope it helps

**Comment by sydwang** [comment]
Thank you for you reply.
I did get the value of Laravel CSRF TOKEN, actually it's the value of XSRF-TOKEN in cookie. But unfortunately, it doesn't work.  The error msg I got was : TokenMismatchException.
Would you help me to solve the problem?
Thank you.

**Comment by cook-coder** [comment]
Whoops, it sounds like the same problem I'v got before. But it doesn't appear recently. Try to make a GET request first, then POST.

**Comment by sydwang** [comment]
I tried according to your guide, but it didn't work.  The error msg was the same.
Any suggestion do you have? 
Thank you.

**Comment by cook-coder** [comment]
加我QQ吧，252446162. 有图才好说。

**Comment by sydwang** [comment]
The value we need to set is X-XSRF-TOKEN, not X-CSRF-TOKEN. 
Do the get request first, then the value of X-XSRF-TOKEN will be set. 
Then the post request can be implemented successfully.
