### ISSUE TITLE
Add to Paw Extensions directory

### ISSUE THREAD

**Issue by martinbean** [FangStarNet/net.fangstar.LaravelCsrfToken#2]
Any chance of this extension getting added to [Paw’s official Extensions directory](https://paw.cloud/extensions/)?

**Comment by cook-coder** [comment]
Thanks for your advise, I will do it asap.

**Comment by martinbean** [comment]
@breezecoder Awesome! 😄 

Came across the issue of testing POST endpoints in a Laravel application myself.

**Comment by cook-coder** [comment]
They've added it to official extensions. [Here it is](https://paw.cloud/extensions?q=Laravel) 😆

**Comment by martinbean** [comment]
@breezecoder Awesome! Thanks for getting on that so quickly. Really appreciate it! 🙂

**Comment by cook-coder** [comment]
It's my pleasure.
